meta_product_name: "Beam"
meta_title: "Beam - Creates connections."
meta_description: "Meet new people, chat and go to concerts, together"
meta_image: "cover.png" # should exist in `app/assets/images/`
